# Generated by Django 4.2.7 on 2024-03-03 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.BigIntegerField()),
                ('dname', models.CharField(max_length=50)),
                ('noOfDoc', models.IntegerField()),
                ('block', models.CharField(max_length=50)),
                ('noOfBeds', models.IntegerField()),
                ('image', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Doctordetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docid', models.BigIntegerField()),
                ('contact', models.IntegerField()),
                ('starting_time', models.TimeField()),
                ('ending_time', models.TimeField()),
                ('mnoOfToken', models.IntegerField()),
                ('anoOfToken', models.IntegerField(default=0)),
                ('enoOfToken', models.IntegerField()),
                ('period', models.CharField(max_length=20)),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinetoken.department')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.BigIntegerField()),
                ('hname', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('image', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.BigIntegerField()),
                ('contact', models.IntegerField()),
                ('reason', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinetoken.department')),
                ('docid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinetoken.doctordetails')),
                ('hid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinetoken.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.BigIntegerField()),
                ('date', models.DateField()),
                ('rating', models.IntegerField()),
                ('content', models.CharField(max_length=100)),
                ('docid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinetoken.doctordetails')),
                ('hid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinetoken.hospital')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinetoken.patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='rid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinetoken.review'),
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='hid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinetoken.hospital'),
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='rid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinetoken.review'),
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='hid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinetoken.hospital'),
        ),
    ]
