# Generated by Django 4.2.7 on 2024-03-03 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetoken', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordetails',
            name='rid',
        ),
    ]
