# Generated by Django 4.2.7 on 2024-03-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetoken', '0002_remove_doctordetails_rid'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetails',
            name='study',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
