# Generated by Django 4.2.7 on 2024-03-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetoken', '0004_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='rid',
        ),
    ]
